name: Deploy GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Create .env file
      run: |
        echo "REACT_APP_EMAIL_USER_ID=${{ secrets.REACT_APP_EMAIL_USER_ID }}" >> .env  # Example for React
        echo "REACT_APP_EMAIL_SERVICE_ID=${{ secrets.REACT_APP_EMAIL_SERVICE_ID }}" >> .env  # Add more as needed
        echo "REACT_APP_EMAIL_TEMPLATE_ID=${{ secrets.REACT_APP_EMAIL_TEMPLATE_ID }}" >> .env

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
